services:
  buildkit:
    image: moby/buildkit:latest
    privileged: true
    command: --addr tcp://0.0.0.0:1234 --addr unix:///run/buildkit/buildkitd.sock
    ports:
      - "1234:1234"
    volumes:
      - buildkit-cache:/var/lib/buildkit
      - ./buildkitd.toml:/etc/buildkit/buildkitd.toml

  autoscaler:
    build:
      context: autoscaler
      dockerfile: ./Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      REGISTRATION_URL: "${REGISTRATION_URL}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      RUNNER_IMAGE: "runner"
      DOCKER_REGISTRY_URL: "${DOCKER_REGISTRY_URL}"
      DOCKER_REGISTRY_USERNAME: "${DOCKER_REGISTRY_USERNAME}"
      DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"

      SCALE_SET_NAME: "local-runner"
      MAX_RUNNERS: "10"
      MIN_RUNNERS: "1"
      LABELS: "linux/amd64,test-1,test-2"
      RUNNER_GROUP: "default"
      DOCKER_HOSTS: "unix:///var/run/docker.sock"
      RUNTIME: "sysbox-runc"
      BUILDKIT_HOST_URL: "tcp://buildkit:1234"

  runner:
    image: runner
    build:
      context: runner
      dockerfile: ./Dockerfile

volumes:
  buildkit-cache:
