services:
  autoscaler:
    build:
      context: autoscaler
      dockerfile: ./Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config.yaml:/app/config.yaml:ro"
    environment:
      REGISTRATION_URL: "${REGISTRATION_URL}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      RUNNER_IMAGE: "${RUNNER_IMAGE}"
      DOCKER_REGISTRY_URL: "${DOCKER_REGISTRY_URL}"
      DOCKER_REGISTRY_USERNAME: "${DOCKER_REGISTRY_USERNAME}"
      DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"
      ARTIFACTORY_TOKEN: "${ARTIFACTORY_TOKEN}"
      CONFIG_FILE_PATH: "/app/config.yaml"

  registry-mirror:
    container_name: registry-mirror
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    image: registry:2
    ports:
      - "5000:5000"

  runner:
    image: runner
    build:
      context: runner
      dockerfile: ./Dockerfile
