name: "Build and Publish"
run-name: "Build and Publish : mgarnier11/autoscaler:${{ github.sha }}"
on:
  push:
    branches:
      - main
    paths:
      - "autoscaler/**"
      - "runner/**"
  workflow_dispatch:

jobs:
  build-autoscaler:
    runs-on: linux/${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Build autoscaler image
        run: |
          docker buildx build \
            --build-arg TARGETPLATFORM=${{ matrix.platform }} \
            --tag mgarnier11/autoscaler:${{ matrix.platform }} \
            --cache-from=type=registry,ref=registry.mgarnier11.fr/autoscaler:buildcache \
            --cache-to=type=registry,ref=registry.mgarnier11.fr/autoscaler:buildcache,mode=max \
            autoscaler

      - name: Push autoscaler image
        run: |
          docker push 'mgarnier11/autoscaler:${{ matrix.platform }}'
  build-runner:
    runs-on: linux/${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Build runner image
        run: |
          docker buildx build \
            --build-arg TARGETPLATFORM=${{ matrix.platform }} \
            --tag mgarnier11/runner:${{ matrix.platform }} \
            --cache-from=type=registry,ref=registry.mgarnier11.fr/runner:buildcache \
            --cache-to=type=registry,ref=registry.mgarnier11.fr/runner:buildcache,mode=max \
            runner

      - name: Push runner image
        run: |
          docker push 'mgarnier11/runner:${{ matrix.platform }}'
  publish:
    runs-on: linux/amd64
    needs: [build-autoscaler, build-runner]
    steps:
      - name: Publish multi-arch images
        run: |
          docker buildx imagetools create \
          --tag mgarnier11/autoscaler:latest \
          --tag mgarnier11/autoscaler:${{ github.sha }} \
          mgarnier11/autoscaler:amd64 \
          mgarnier11/autoscaler:arm64

          docker buildx imagetools create \
          --tag mgarnier11/runner:latest \
          --tag mgarnier11/runner:${{ github.sha }} \
          mgarnier11/runner:amd64 \
          mgarnier11/runner:arm64
